baseURL = "https://boroooo.github.io/"
languageCode = "en-us"
title = "SCHOLAR | BAORIAN"
theme = "avicenna"
enableEmoji = true

# Google Analytics（可留空或换成你的真实 ID）
googleAnalytics = "UA/G-123123-12"

[pagination]
  pagerSize = 10

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[params]
  name = "BAORIAN"

# 顶部菜单（把 Projects 放出来）
[menu]
  [[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 30
  [[menu.main]]
    name = "Publications"
    url  = "/publications/"
    weight = 20
  [[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 40
  [[menu.main]]
    name = "News"
    url  = "/news/"
    weight = 50
